const langData = {
    "ko": {
        "footer_title": "TradingDiaryPro",
        "footer_desc": "암호화폐 및 주식 투자자를 위한 올인원 매매일지 및 분석 도구입니다. 복잡한 시장 데이터를 한눈에 파악하고, 개인의 투자 기록을 체계적으로 관리하며, 심층적인 분석을 통해 투자 전략을 개선할 수 있도록 돕습니다.",
        "features_title": "주요 기능",
        "feature_1": "실시간 코인 가격 및 알림",
        "feature_2": "매매일지 작성 및 관리",
        "feature_3": "성과 지표 대시보드",
        "feature_4": "다국어 지원",
        "feature_5": "데이터 내보내기/가져오기",
        "usage_title": "TradingDiaryPro 사용법",
        "usage_1": "회원가입 및 로그인 (로컬 저장소 기반)",
        "usage_2": "대시보드 확인",
        "usage_3": "매매일지 작성",
        "usage_4": "거래 내역 관리",
        "usage_5": "알림 설정",
        "usage_6": "데이터 백업 및 복원",
        "support_title": "문의 및 지원",
        "support_email": "이메일: ",
        "copyright": "© 2025 TradingDiaryPro. All rights reserved."
    },
    "en": {
        "footer_title": "TradingDiaryPro",
        "footer_desc": "TradingDiaryPro is an all-in-one trading journal and analysis tool for cryptocurrency and stock investors. It helps you grasp complex market data at a glance, systematically manage your personal investment records, and improve your investment strategies through in-depth analysis.",
        "features_title": "Key Features",
        "feature_1": "Real-time Coin Prices & Alerts",
        "feature_2": "Trading Journal Creation & Management",
        "feature_3": "Performance Metrics Dashboard",
        "feature_4": "Multi-language Support",
        "feature_5": "Data Export/Import",
        "usage_title": "How to Use TradingDiaryPro",
        "usage_1": "Sign Up & Log In (Local Storage Based)",
        "usage_2": "Check Dashboard",
        "usage_3": "Create Trading Journal",
        "usage_4": "Manage Transaction History",
        "usage_5": "Set Up Alerts",
        "usage_6": "Data Backup & Restore",
        "support_title": "Inquiries & Support",
        "support_email": "Email: ",
        "copyright": "© 2025 TradingDiaryPro. All rights reserved."
    },
    "ja": {
        "footer_title": "TradingDiaryPro",
        "footer_desc": "TradingDiaryProは、仮想通貨および株式投資家向けのオールインワントレード日誌および分析ツールです。複雑な市場データを一目で把握し、個人の投資記録を体系的に管理し、詳細な分析を通じて投資戦略を改善するのに役立ちます。",
        "features_title": "主な機能",
        "feature_1": "リアルタイムコイン価格とアラート",
        "feature_2": "トレード日誌の作成と管理",
        "feature_3": "パフォーマンス指標ダッシュボード",
        "feature_4": "多言語対応",
        "feature_5": "データのエクスポート/インポート",
        "usage_title": "TradingDiaryProの使用方法",
        "usage_1": "サインアップとログイン（ローカルストレージベース）",
        "usage_2": "ダッシュボードの確認",
        "usage_3": "トレード日誌の作成",
        "usage_4": "取引履歴の管理",
        "usage_5": "アラートの設定",
        "usage_6": "データのバックアップと復元",
        "support_title": "お問い合わせとサポート",
        "support_email": "メール: ",
        "copyright": "© 2025 TradingDiaryPro. All rights reserved."
    },
    "zh": {
        "footer_title": "TradingDiaryPro",
        "footer_desc": "TradingDiaryPro是一款专为加密货币和股票投资者设计的一体化交易日志和分析工具。它帮助您一目了然地掌握复杂的市场数据，系统地管理您的个人投资记录，并通过深入分析改进您的投资策略。",
        "features_title": "主要功能",
        "feature_1": "实时币价和提醒",
        "feature_2": "交易日志创建与管理",
        "feature_3": "绩效指标仪表板",
        "feature_4": "多语言支持",
        "feature_5": "数据导出/导入",
        "usage_title": "TradingDiaryPro使用方法",
        "usage_1": "注册与登录（基于本地存储）",
        "usage_2": "查看仪表板",
        "usage_3": "创建交易日志",
        "usage_4": "管理交易历史",
        "usage_5": "设置提醒",
        "usage_6": "数据备份与恢复",
        "support_title": "咨询与支持",
        "support_email": "电子邮件: ",
        "copyright": "© 2025 TradingDiaryPro. All rights reserved."
    },
    "es": {
        "footer_title": "TradingDiaryPro",
        "footer_desc": "TradingDiaryPro es una herramienta todo en uno de diario de trading y análisis para inversores de criptomonedas y acciones. Le ayuda a comprender datos complejos del mercado de un vistazo, gestionar sistemáticamente sus registros de inversión personales y mejorar sus estrategias de inversión mediante un análisis en profundidad.",
        "features_title": "Características Principales",
        "feature_1": "Precios y Alertas de Monedas en Tiempo Real",
        "feature_2": "Creación y Gestión de Diario de Trading",
        "feature_3": "Panel de Métricas de Rendimiento",
        "feature_4": "Soporte Multilingüe",
        "feature_5": "Exportación/Importación de Datos",
        "usage_title": "Cómo Usar TradingDiaryPro",
        "usage_1": "Registro e Inicio de Sesión (Basado en Almacenamiento Local)",
        "usage_2": "Ver Panel de Control",
        "usage_3": "Crear Diario de Trading",
        "usage_4": "Gestionar Historial de Transacciones",
        "usage_5": "Configurar Alertas",
        "usage_6": "Copia de Seguridad y Restauración de Datos",
        "support_title": "Consultas y Soporte",
        "support_email": "Correo electrónico: ",
        "copyright": "© 2025 TradingDiaryPro. All rights reserved."
    }
};

